<?php
module_load_include('inc', 'species', 'phpflickr');
/**
* Implementation of hook_menu()
**/
function species_menu() {
  $items = array();

  // Species display 
  $items['species/%/%'] = array(
    'title' => 'Species Information',
    'access arguments' => array('access content'),
    'page callback' => 'species_display',
    'page arguments' => array(1,2),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}

/**
*  Page callback
**/
function species_display($db_table, $ibp_id){
  global $db_type;
  $output = '';
  $prev_col = array();
  $sql = 'select * from '.$db_table.' where ibp_id = %d';
  $row = db_fetch_array(db_query($sql,array($ibp_id)));
  $col_num = 1;
  $row_no = 0;

 //get the italics columns for the grt from Meta_Global_Resource table
   $qry = "select italics_columns from \"Meta_Global_Resource\" where resource_tablename = '".$db_table."'";
  $res = db_query($qry);
  $rw = db_fetch_array($res);
  $italics_col = explode(',',$rw['italics_columns']);


//images from flickr
  //require_once('phpFlickr/phpFlickr.php');
  $f = new phpFlickr("40059d14fc8c9915f0621568d61d9023", "41712609f787b238");
  $flickr_photos = array();
  $flickr_photos = $f->photos_search(array("tags"=>$row['ibp_scientific_name'], "tag_mode"=>"any"));
  for($i=0;$i < 9;$i++)
  {
    	$url = "http://farm".$flickr_photos['photo'][$i]['farm'].".static.flickr.com/".$flickr_photos['photo'][$i]['server']."/".$flickr_photos['photo'][$i]['id']."_".$flickr_photos['photo'][$i]['secret']."_s.jpg";
    	$link_url = "http://www.flickr.com/photos/".$flickr_photos['photo'][$i]['owner']."/".$flickr_photos['photo'][$i]['id']."/";
    	$output .= "<a href='".$link_url."'><img src='".$url."' border='1' title='".($flickr_photos['photo'][$i]['title']?$flickr_photos['photo'][$i]['title']:$flickr_photos['photo'][$i]['id'])."' style='margin:2px 2px 2px 2px;'/></a>";
//$output .= $flickr_photos['photo'][$i]['title'];
  }
  $output .= '<br /><span class=\'flickr_more\'><a href=\'#flickr_photos\'>more...</a></span>';
 
  $output .= '<table class="speciesTable">';
  $output .= '<tr>';
  $output .= '<th>Key</th>';
  $output .= '<th>Value</th>';
  $output .= '</tr>';
  foreach($row as $column=>$value) {
    $description = '';
    if($db_type == 'pgsql') {
      $sql = 'select distinct oid from pg_catalog.pg_class where relname = \'%s\'';
      $data_array = array(
        $db_table,
      );
      // Get the oid
      $result = db_query($sql,$data_array);
      $nrow = db_fetch_object($result);
      $oid = $nrow->oid;
      $sql = 'select distinct col_description (%d, %d) from pg_catalog.pg_description';
      $data_array = array(
        $oid,
        $col_num,
      );
      $result = db_query($sql, $data_array);
      //pg_result_seek($result,2) ;
      $nrow = db_fetch_object($result);
      $description = $nrow->col_description;
      $col_num = $col_num + 1;
      //$output .= $description;
    }
    $prev_col[$row_no] = $description;
    //if ($row_no > 0 && ($prev_col[$row_no]<>$prev_col[$row_no - 1]))
  
    //set the scientific_name columns to italics
    for($i=0;$i<count($italics_col);$i++)
    {
      if ($row[$italics_col[$i]] == $value)
      {
        $value = "<em>".$value."</em>";
      }
    }


  if ($row_no > 0)
    {
    $output .= '<tr>';
    if($description) {
      $output .= '<td class="key">'. $description . '</td><td>' . check_markup($value, 1) . '</td>';
    }
    else {
      $output .= '<td class="key">'. $column. '</td><td>' . check_markup($value, 1) . '</td>';
    }
    
    $output .= '</tr>';
    }
    $row_no = $row_no + 1;
  }
  $output .= '</table>';
  $output .= '<a name=\'flickr_photos\'></a><span class="disclaimer">Disclaimer: The India Biodiversity Portal is not responsible for the content or reliability of external websites which are linked to from this website</span><br />';
  $output .= "<h4>Images from Flikr for the species ".$row['ibp_scientific_name']."</h4>";
  if(sizeof($flickr_photos['photo']) == 0)
  {
    $output .= 'No media found on <a href="http://www.flickr.com">Flickr</a>.';
  }
  else
  {
  foreach ($flickr_photos['photo'] as $photo)
  {
    $url = "http://farm".$photo['farm'].".static.flickr.com/".$photo['server']."/".$photo['id']."_".$photo['secret']."_s.jpg";
    $link_url = "http://www.flickr.com/photos/".$photo['owner']."/".$photo['id']."/";
    $output .= "<a href='".$link_url."'><img src='".$url."' border='1' title='".($photo['title']?$photo['title']:$photo['id'])."' style='margin:2px 2px 2px 2px;'/></a>";
  }
  }
  return($output);
}
