<?php
/**
* Implementation of hook_menu()
**/
function species_pages_menu() {
  $items = array();

  // Species pages display 
  $items['species'] = array(
    'title' => 'Species Pages',
    'access arguments' => array('access content'),
    'page callback' => 'species_pages_display',
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}

/**
*  Page callback
**/
function species_pages_display($arg){
  $output = <<<EOD
<div id="species_main_wrapper">

<div class="list">
<h3>Sample species</h3>
<ul>
        <li><a href="http://pamba.strandls.com:8080/species/species/show1/194"><i>Mangifera indica</i> L. 1753</a></li>
        <li><a href="http://pamba.strandls.com:8080/species/species/show1/647"><i>Francolinus pondicerianus</i></a></li>

</ul>
</div>

<div id="species_proto">
<img alt="species prototype" src="/sites/all/themes/wg/images/species_proto.jpg"/>
</div>
</div> 
EOD;

  return($output);
}

